In [1]:
# Input beta
import numpy as np
beta = np.array([[0.396079016, 0.588378706, 0.015542278],
                 [0.864092195, 0.149660857, -0.013753052],
                 [0.486091805, 0.485185136, 0.028723059],
                 [0.056257739, 0.654415236, 0.289327025],
                 [0.201769299, 0.643015532, 0.155215169]])

# Input s
s = np.array([1, 0, -1])

# Calculate e; = Σ Sa
e11 = np.einsum('ij,j->i', beta, s)
print(e11)

[ 0.38053674  0.87784525  0.45736875 -0.23306929  0.04655413]


In [2]:
# Input beta
import numpy as np
beta = np.array([[0.405548878,0.581720341,0.012730781],
                 [0.867333705,0.146807239,-0.014140944],
                 [0.498000692,0.477251066,0.024748241],
                 [0.066133985,0.65009584,0.283770175],
                 [0.230038167,0.64137657,0.128585263]])

# Input s
s = np.array([1, 0, -1])

# Calculate e; = Σ Sa
e12 = np.einsum('ij,j->i', beta, s)
print(e12)

[ 0.3928181   0.88147465  0.47325245 -0.21763619  0.1014529 ]


In [3]:
# Input beta
import numpy as np
beta = np.array([[0.475544797,0.510112788,0.014342415],
                 [0.858594204,0.154071771,-0.012665975],
                 [0.506242578,0.469415975,0.024341447],
                 [0.059902928,0.638357036,0.301740036],
                 [0.255344977,0.659784461,0.084870562]])

# Input s
s = np.array([1, 0, -1])

# Calculate e; = Σ Sa
e13 = np.einsum('ij,j->i', beta, s)
print(e13)

[ 0.46120238  0.87126018  0.48190113 -0.24183711  0.17047441]


In [4]:
# Input beta
import numpy as np
beta = np.array([[0.401524901,0.590179588,0.008295511],
                 [0.86617756,0.148329685,-0.014507245],
                 [0.523228843,0.452713946,0.024057211],
                 [0.099823198,0.652858976,0.247317826],
                 [0.238697121,0.654787277,0.106515602]])
# Input s
s = np.array([1, 0, -1])

# Calculate e; = Σ Sa
e14 = np.einsum('ij,j->i', beta, s)
print(e14)

[ 0.39322939  0.88068481  0.49917163 -0.14749463  0.13218152]


In [11]:
result_matrix = np.vstack((e11, e12, e13, e14)).T

In [12]:
print(result_matrix)

[[ 0.38053674  0.3928181   0.46120238  0.39322939]
 [ 0.87784525  0.88147465  0.87126018  0.88068481]
 [ 0.45736875  0.47325245  0.48190113  0.49917163]
 [-0.23306929 -0.21763619 -0.24183711 -0.14749463]
 [ 0.04655413  0.1014529   0.17047441  0.13218152]]


In [ ]:
def cdf(x, s, S, B):
    if x < S[0]:
        return 0
    elif S[0] <= x < S[1]:
        return s[0] * B
    elif S[1] <= x < S[2]:
        return s[0] * B + s[1] * B
    elif S[2] <= x:
        return s[0] * B + s[1] * B + s[2] * B
    else:
        raise ValueError("x is out of range.")

# Define the input data in base b
base = 3  # Replace with the actual base value.
input_data = [
    [0.396079016 * base, 0.588378706 * base, 0.015542278 * base],
    [0.864092195 * base, 0.149660857 * base, -0.013753052 * base],
    [0.486091805 * base, 0.485185136 * base, 0.028723059 * base],
    [0.056257739 * base, 0.654415236 * base, 0.289327025 * base],
    [0.201769299 * base, 0.643015532 * base, 0.155215169 * base]
]

S = [0, 0.4, 0.8, 1]  # Replace with the actual points if they are different.
B = 0.1  # Replace B with the actual value if it is different.

# Calculate CDFs for each random variable
X = [lambda x: cdf(x, s, S, B) for s in input_data]

a, b = 0, 1

for i, _ in enumerate(X):
    for j, _ in enumerate(X):
        if i != j:
            print(f"First degree dominance between X{i} and X{j}:")
            print(first_degree_stochastic_dominance(X[i], X[j], a, b))

            print(f"Second degree dominance between X{i} and X{j}:")
            print(second_degree_stochastic_dominance(X[i], X[j], a, b))

            print(f"Third degree dominance between X{i} and X{j}:")
            print(third_degree_stochastic_dominance(X[i], X[j], a, b))

In [ ]:
import numpy as np

def compute_cumulative_distribution_function(Fij):
    # This function computes the cumulative distribution function Fij
    # Implementation details are not provided in the context
    pass

def compare_fij(Fij, FSD, SSD, TSD, p, ;;):
    if Fij > FSD * Fij:
        return 'FSDA concerning C'
    elif Fij > SSD * Fij:
        return 'SSDA concerning C'
    elif Fij < TSD * Fkj:
        return 'A₁ TSD Ak concerning C'
    else:
        return 'no SD relation'

def compute_degree_of_preference(A₁, Ak, C):
    # This function computes the degree of preference P(A₁, Ak) concerning C
    # Implementation details are not provided in the context
    pass

def compute_net_flow(A, C, w, 1):
    # This function computes the net flow (A;)
    # Implementation details are not provided in the context
    pass

def rank_products(F, FSD, SSD, TSD, p, ;;, w, 1):
    n = len(F[0])
    m = len(F)
    D = np.zeros((m, n))

    # Compute the cumulative distribution function Fij
    for j in range(n):
        Fij = compute_cumulative_distribution_function(F[:, j])
        for i in range(m):
            for k in range(m):
                if i != k:
                    comparison_result = compare_fij(Fij[i], Fij[k], FSD, SSD, TSD, p, ;;)
                    if comparison_result == 'FSDA concerning C':
                        D[i, j] += 1
                    elif comparison_result == 'SSDA concerning C':
                        D[k, j] += 1
                    elif comparison_result == 'A₁ TSD Ak concerning C':
                        D[k, j] += 1

    # Compute the net flow for each attribute
    for j in range(n):
        for i in range(m):
            for k in range(m):
                if i != k:
                    A₁, Ak = D[i, j], D[k, j]
                    P = compute_degree_of_preference(A₁, Ak, C)
                    D[i, j] = P
                    D[k, j] = -P
        A = sum(D[:, j])
        compute_net_flow(A, C, w, 1)

    return D